# Generated by Django 2.1.7 on 2019-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('datePublication', models.DateTimeField(verbose_name='datePublication')),
                ('marque', models.CharField(max_length=60)),
                ('modele', models.CharField(max_length=60)),
                ('boiteVitesse', models.CharField(max_length=30)),
                ('puissanceFiscale', models.IntegerField(default=0)),
                ('energie', models.CharField(max_length=60)),
                ('kilometrage', models.IntegerField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('personne', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personne_physique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.IntegerField(default=0)),
                ('adresse', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('identifiant', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
