# Generated by Django 2.1.7 on 2019-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoprix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='gallerie/'),
        ),
    ]
