# Generated by Django 2.1.7 on 2019-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoprix', '0002_annonce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(default='default_car.jpg', upload_to='gallerie/'),
        ),
    ]
